/**
 * Book title -> author(s) for the /audible Books picker filter.
 *
 * GENERATED from audible-kb deep-note frontmatter (`title` /
 * `author_assumed` in ~/audible-kb/kb/books/*.md), keyed by the exact
 * frontmatter title the sync script posts, so keys match the labels the
 * Books picker renders. Books absent from this map (unknown-author
 * catalog artifacts, or titles added after generation) fall back to
 * title-only filtering. Regenerate by re-running the frontmatter
 * export from the audible-kb repo (see that repo's scripts/).
 */
export const AUDIBLE_BOOK_AUTHORS: Record<string, string> = {
  "$100M Offers: How to Make Offers So Good People Feel Stupid Saying No": "Alex Hormozi",
  "1% Better: Reaching My Full Potential and How You Can Too": "Chris Nikic, Nik Nikic, Don Yaeger",
  "100 Ways to Create Wealth": "Sam Beckford, Steve Chandler",
  "101 Lessons I Learnt From Richard Branson": "Jamie McIntyre",
  "10x Is Easier than 2x: How World-Class Entrepreneurs Achieve More by Doing Less": "Dan Sullivan, Benjamin Hardy",
  "12 Months to $1 Million: How to Pick a Winning Product, Build a Real Business, and Become a Seven-Figure Entrepreneur": "Ryan Daniel Moran",
  "20,000 Days and Counting: The Crash Course for Mastering Your Life Right Now": "Robert D. Smith",
  "21 Days of Meditation": "Aaptiv",
  "21 Success Secrets of Self-Made Millionaires": "Brian Tracy",
  "33 Fiverr Gigs That Sell Like Crazy: Featuring Proven Job Ideas Used by Top Sellers": "Dan Howe",
  "4 Ways to Stop Self-Sabotage": "Judy Ho",
  "50 Ways To Motivate Yourself In 50 Minutes: Discover 50 Motivational Hacks To Build Self-Discipline, Achieve Your Goals And Get What You Want": "Riley Stevens",
  "6 Months to 6 Figures": "Peter J. Voogd",
  "8 Lessons in Military Leadership for Entrepreneurs": "Robert T. Kiyosaki",
  "90 Minutes in Heaven: A True Story of Death & Life": "Don Piper",
  "A Brief History of Time": "Stephen Hawking",
  "A Discourse on Method: Meditations on the First Philosophy: Principles of Philosophy": "Ren\u00e9 Descartes",
  "A Gospel of Hope": "Walter Brueggemann",
  "A Grief Observed": "C. S. Lewis",
  "A Healthy Dose of Motivation: Includes 'The Aladdin Factor' and 'Dare to Win'": "Jack Canfield, Mark Victor Hansen",
  "A Knock at Midnight": "Clayborne Carson",
  "A Man Called Ove: A Novel": "Fredrik Backman",
  "A Million Miles in a Thousand Years: What I Learned While Editing My Life": "Donald Miller",
  "A Passion for Nature: The Life of John Muir": "Donald Worster",
  "A Return to Love": "Marianne Williamson",
  "A Sense of Urgency Creates Great Work": "Bob Proctor",
  "A Spirituality for the Two Halves of Life": "Richard Rohr O.F.M., Paula D'Arcy",
  "A Torch Kept Lit: Great Lives of the Twentieth Century": "William F. Buckley",
  "ABCs of Real Estate Investing: The Secrets of Finding Hidden Profits Most Investors Miss": "Ken McElroy",
  "AI Riches: Make Money with ChatGPT: How I Made $10K a Month Talking to a Robot (And How You Can Too)": "Mark Miller",
  "Abounding Grace: An Anthology of Wisdom": "M. Scott Peck M.D.",
  "Above All: The Gospel Is the Source of the Church's Renewal": "J.D. Greear",
  "Acres of Diamonds": "Russell H. Conwell",
  "Acres of Diamonds of Russell Conwell, by Earl Nightingale": "Earl Nightingale",
  "Act Like a Success, Think Like a Success: Discovering Your Gift and the Way to Life's Riches": "Steve Harvey",
  "Affiliate Marketing: Learn How to Make $10,000+ Each Month on Autopilot (Passive Income, Make Money Online and Financial Freedom Series)": "Michael Ezeanaka",
  "After: A Doctor Explores What Near-Death Experiences Reveal about Life and Beyond": "M.D. Bruce Greyson",
  "All It Takes Is a Goal: The 3-Step Plan to Ditch Regret and Tap into Your Massive Potential": "Jon Acuff",
  "All My Knotted-Up Life: A Memoir": "Beth Moore",
  "Altogether You: Experiencing Personal and Spiritual Transformation with Internal Family Systems Therapy": "Jenna Riemersma",
  "Always Be the Buyer: Attracting Other People's Highest Commitment to Your Biggest and Best Standards": "Dan Sullivan",
  "Amazing Grace: William Wilberforce and the Heroic Campaign to End Slavery": "Eric Metaxas",
  "America's Real War": "Rabbi Daniel Lapin",
  "American Legends: The Life of Henry Ford": "Charles River Editors",
  "American Legends: The Life of J. P. Morgan": "Charles River Editors",
  "An Effective Life: Inspirational Philosophy from Dr. Covey's Life": "Stephen R. Covey",
  "Anatomy of the Spirit: A Caroline Myss Original Audio Workshop": "Caroline Myss",
  "Andrew Murray Collection: Humility, Absolute Surrender, and With Christ in the School of Prayer": "Andrew Murray",
  "Applying the Business Model Canvas: A Practical Guide for Small Business: Design, Align and Test Your Ideas": "Steven Imke",
  "As a Man Thinketh": "James Allen",
  "As a Man Thinketh and From Poverty to Power": "James Allen",
  "Ask and It Is Given: Learning to Manifest Your Desires": "Esther Hicks, Jerry Hicks",
  "Ask!: The Bridge from Your Dreams to Your Destiny": "Mark Victor Hansen, Crystal Dwyer Hansen",
  "Ask: The Counterintuitive Online Formula to Discover Exactly What Your Customers Want to Buy...Create a Mass of Raving Fans...and Take Any Business to the Next Level": "Ryan Levesque",
  "At Your Best: How to Get Time, Energy, and Priorities Working in Your Favor": "Carey Nieuwhof",
  "Attached: The New Science of Adult Attachment and How It Can Help You Find\u2014and Keep\u2014Love": "Amir Levine, Rachel Heller",
  "Awaken the Giant Within": "Tony Robbins",
  "BE 2.0 (Beyond Entrepreneurship 2.0): Turning Your Business into an Enduring Great Company": "Jim Collins, William Lazier",
  "Banker to the Poor: Micro-Lending and the Battle against World Poverty": "Muhammad Yunus",
  "Be All You Can Be: A Challenge to Stretch Your God-Given Potential": "John C. Maxwell",
  "Be Creative: Essential Steps To Revitalise Your Life": "BBC, Bill Lucas, Guy Claxton",
  "Be Obsessed Or Be Average": "Grant Cardone",
  "Be Useful: Seven Tools for Life": "Arnold Schwarzenegger",
  "Be Your Future Self Now: The Science of Intentional Transformation": "Benjamin Hardy",
  "Be a People Person: Effective Leadership Through Effective Relationships": "John C. Maxwell",
  "Beautiful Outlaw: Experiencing the Playful, Disruptive, Extravagant Personality of Jesus": "John Eldredge",
  "Beautifully Imperfect: Love Yourself First": "Craig Beck",
  "Becoming Rich: A Method for Manifesting Exceptional Wealth (A Course in Manifesting)": "Genevieve Davis",
  "Bedtime Affirmations: Positive Daily Affirmations to Aid You Take a Peaceful Sleep Free of Worries Using the Law of Attraction, Self-Hypnosis, Guided Meditation and Sleep Learning": "Stephens Hyang",
  "Beginning with Gratitude": "The Big Quiet, Audible Sleep",
  "Between Death and Life: Conversations with a Spirit": "Dolores Cannon",
  "Beyond Order: 12 More Rules for Life": "Jordan B. Peterson",
  "Billy Graham: The Man I Knew": "Greg Laurie, Marshall Terrill",
  "Biography: Abraham Lincoln": "A&E Television Networks",
  "Biography: Adam & Eve": "A&E Television Networks",
  "Biography: Amelia Earhart": "A&E Television Networks",
  "Biography: Benjamin Franklin": "A&E Television Networks",
  "Biography: George Washington": "A&E Television Networks",
  "Biography: Jesus": "A&E Television Networks",
  "Biography: John F. Kennedy": "A&E Television Networks",
  "Biography: Mary of Nazareth": "A&E Television Networks",
  "Biography: Michelangelo": "A&E Television Networks",
  "Biography: Moses (Parts 1 and 2)": "A&E Television Networks",
  "Biography: Samson & Delilah": "A&E Television Networks",
  "Biography: Solomon & Sheba": "A&E Television Networks",
  "Biography: Thomas Jefferson": "A&E Television Networks",
  "Blessed Are the Misfits: Great News for Believers who are Introverts, Spiritual Strugglers, or Just Feel Like They're Missing Something": "Brant Hansen",
  "Blink: The Power of Thinking Without Thinking": "Malcolm Gladwell",
  "Blue Like Jazz: Non-Religious Thoughts on Christian Spirituality": "Donald Miller",
  "Bob Proctor - World Authority on Prosperity: Conversations with the Best Entrepreneurs on the Planet": "Bob Proctor",
  "Born to Win: Find Your Success": "Zig Ziglar, Tom Ziglar",
  "Boundaries for Leaders: Results, Relationships, and Being Ridiculously in Charge": "Henry Cloud",
  "Brain Rules: 12 Principles for Surviving and Thriving at Work, Home, and School": "John J. Medina",
  "Braving the Wilderness: The Quest for True Belonging and the Courage to Stand Alone": "Bren\u00e9 Brown",
  "Breaking the Habit of Being Yourself": "Dr. Joe Dispenza",
  "Breaking the Habit of Being Yourself: How to Lose Your Mind and Create a New One": "Dr. Joe Dispenza",
  "Breakthrough: Overcoming Obstacles and Breaking Barriers in Business and Life": "Made for Success",
  "Building a StoryBrand: Clarify Your Message So Customers Will Listen": "Donald Miller",
  "Built to Sell: Creating a Business That Can Thrive Without You": "John Warrillow",
  "Bull's-Eye: The Power of Focus": "Brian Tracy",
  "Business @ the Speed of Thought: Succeeding in the Digital Economy": "Bill Gates",
  "Business Secrets from the Bible: Spiritual Success Strategies for Financial Abundance": "Daniel Lapin",
  "Buy Back Your Time: Get Unstuck, Reclaim Your Freedom, and Build Your Empire": "Dan Martell",
  "Called to Create: A Biblical Invitation to Create, Innovate, and Risk": "Jordan Raynor",
  "Can Man Live without God": "Ravi Zacharias",
  "Can't Hurt Me: Master Your Mind and Defy the Odds": "David Goggins",
  "Cash in a Flash: Real Money in No Time": "Mark Victor Hansen, Robert G. Allen",
  "Centering Prayer and Inner Awakening": "Cynthia Bourgeault",
  "Challenge Your Potential": "Bob Proctor",
  "Challenge of Jesus: Rediscovering Who Jesus Was and Is": "N.T. Wright",
  "Change Your Paradigm, Change Your Life": "Bob Proctor",
  "ChatGPT Wealth Blueprint: Mastering AI for Maximum ROI \u2013 The Definitive 3-in-1 Guide": "Jordan Ashwood",
  "Chicken Soup for Entrepreneur's Soul: Advice and Inspiration for Fulfilling Dreams": "Jack Canfield, Mark Victor Hansen",
  "Chicken Soup for the Soul: Think Positive: 101 Inspirational Stories about Counting Your Blessings and Having a Positive Attitude": "Jack Canfield, Mark Victor Hansen, Amy Newmark, Deborah Norville - foreword",
  "Choose Them Wisely: Thoughts Become Things!": "Mike Dooley",
  "Choose Your Story, Change Your Life: Silence Your Inner Critic and Rewrite Your Life from the Inside Out": "Kindra Hall",
  "Choose Yourself!: Be Happy, Make Millions, Live the Dream": "James Altucher",
  "Christian Faith and Same Sex Attraction: Eastern Orthodox Reflections": "Thomas Hopko",
  "Click Millionaires: Work Less, Live More with an Internet Business You Love": "Scott Fox",
  "Co-Intelligence: Living and Working with AI": "Ethan Mollick",
  "Coach Builder: How to Turn Your Expertise Into a Profitable Coaching Career": "Donald Miller",
  "Codependent No More: How to Stop Controlling Others and Start Caring for Yourself": "Melody Beattie",
  "Communication and the Art of Persuasion": "Jim Rohn",
  "Compassion in the Court: Life-Changing Stories from America's Nicest Judge": "Judge Frank Caprio",
  "Confident Financial Planning: How to Build, Protect, and Enjoy Your Money": "Paul Winkler",
  "Contagious: Why Things Catch On": "Jonah Berger",
  "Control Your Inner Conversations: Neville Goddard Lectures": "Neville Goddard",
  "Courageous Leadership": "Bill Hybels",
  "Creativity, Inc.: Overcoming the Unseen Forces That Stand in the Way of True Inspiration": "Ed Catmull, Amy Wallace",
  "Cross Roads": "Wm. Paul Young",
  "Crush It!: Why NOW Is the Time to Cash In on Your Passion": "Gary Vaynerchuk",
  "Crushing: God Turns Pressure into Power": "T. D. Jakes",
  "Culture Shifts and Paradigms": "Bob Proctor",
  "Daddy's Gone A Hunting": "Mary Higgins Clark",
  "Daily Rituals: How Artists Work": "Mason Currey",
  "Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead": "Bren\u00e9 Brown PhD LMSW",
  "Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead by Brene Brown: 30-Minute Expert Summary": "30 Minute Expert Summary",
  "Declutter Your Way to Success": "Terri Savelle Foy Ministries",
  "Deep D.O.S. Innovation: Create Unique Value for Your Clients by Helping Them Transform Their Dangers, Opportunities, and Strengths.": "Dan Sullivan",
  "Deep Work: Rules for Focused Success in a Distracted World": "Cal Newport",
  "Deep and Wide: Creating Churches Unchurched People Love to Attend": "Andy Stanley",
  "Destiny: Step into Your Purpose": "T. D. Jakes",
  "Dianetics: The Modern Science of Mental Health": "L. Ron Hubbard",
  "Digital Minimalism: Choosing a Focused Life in a Noisy World": "Cal Newport",
  "Discipline Is Destiny: The Power of Self-Control": "Ryan Holiday",
  "Disciplines of a Godly Man": "R. Kent Hughes",
  "Do Epic Shit": "Ankur Warikoo",
  "Do Over: Rescue Monday, Reinvent Your Work, and Never Get Stuck": "Jon Acuff",
  "Do You!: 12 Laws to Access the Power in You to Achieve Happiness and Success": "Russell Simmons, Chris Morrow",
  "Do the Work: The Official Unrepentant, Ass-Kicking, No-Kidding, Change-Your-Life Sidekick to Unfu*k Yourself": "Gary John Bishop",
  "Dollars and Sense: How We Misthink Money and How to Spend Smarter": "Dan Ariely, Jeff Kreisler",
  "Dolly Parton, Songteller: My Life in Lyrics": "Dolly Parton",
  "Don't Believe Everything You Think (Expanded Edition): Why Your Thinking Is The Beginning & End Of Suffering": "Joseph Nguyen",
  "Don't Give the Enemy a Seat at Your Table: It's Time to Win the Battle of Your Mind...": "Louie Giglio",
  "Dream Big: Know What You Want, Why You Want It, and What You're Going to Do About It": "Bob Goff",
  "Dream It. Pin It. Live It.: Make Vision Boards Work for You": "Terri Savelle Foy",
  "Dream More: Celebrate the Dreamer in You": "Dolly Parton",
  "Dreams Don't Have Deadlines: Living Your Dream Life, No Matter What Your Age": "Mark Victor Hansen",
  "Drive: The Surprising Truth About What Motivates Us": "Daniel H. Pink",
  "Dying to Wake Up: A Doctor's Voyage into the Afterlife and the Wisdom He Brought Back": "Rajiv Parti M.D. M.D., Paul Perry, Raymond Moody - introduction Jr. M.D. Ph.D. M.D. Ph.D.",
  "ESV Hear the Word Audio Bible: The Bible for Life": "Crossway",
  "Early Retirement Extreme: A Philosophical and Practical Guide to Financial Independence": "Jacob Lund Fisker",
  "Earth (The Audiobook) Free Chapter": "Jon Stewart",
  "Ego Free Leadership: Ending the Unconscious Habits That Hijack Your Business": "Brandon Black, Shayne Hughes",
  "Einstein: His Life and Universe": "Walter Isaacson",
  "Elon Musk": "Walter Isaacson, Walter Isaacson - introduction",
  "Embracing Rhythms of Work and Rest: From Sabbath to Sabbatical and Back Again": "Ruth Haley Barton",
  "Emotional Intelligence: Why It Can Matter More Than IQ": "Daniel Goleman Ph.D.",
  "Emotionally Healthy Spirituality: It's Impossible to Be Spiritually Mature, While Remaining Emotionally Immature": "Peter Scazzero",
  "Empty Out the Negative: Make Room for More Joy, Greater Confidence, and New Levels of Influence": "Joel Osteen",
  "Enemies of the Heart: Breaking Free from the Four Emotions That Control You": "Andy Stanley",
  "Entangled Minds: Extrasensory Experiences in a Quantum Reality": "Dean Radin Ph.D.",
  "Ep. 1: A Wild Antidote": "Florence Williams",
  "Ep. 2: Floating Through PTSD": "Florence Williams",
  "Ep. 3: A Place of Comfort": "Florence Williams",
  "Ep. 4: Nature is the Best Caffeine": "Florence Williams",
  "Ep. 5: Crunching the Nature Data": "Florence Williams",
  "Ep. 6: The Big Awesome": "Florence Williams",
  "Epic: The Story God Is Telling and the Role That Is Yours to Play": "John Eldredge",
  "Episode 1: Point to the Sky": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Episode 2: From Bullets to Paddles - Part 1": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Episode 3: From Bullets to Paddles - Part 2": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Episode 4: Course of Justice - Part 1": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Episode 5: Course of Justice - Part 2": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Episode 6: It's Showtime! - Part 1": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Episode 7: It's Showtime! - Part 2": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Essentialism: The Disciplined Pursuit of Less": "Greg McKeown",
  "Eve": "Wm. Paul Young",
  "Everybody, Always: Becoming Love in a World Full of Setbacks and Difficult People": "Bob Goff",
  "Everyday Meditation": "Aaptiv",
  "Everywhere You Look: Discovering the Church Right Where You Are": "Tim Soerens, Walter Brueggemann - foreword",
  "Evil and the Justice of God": "N.T. Wright",
  "Experiencing Grief": "H. Norman Wright",
  "Expert Secrets: The Underground Playbook for Creating a Mass Movement of People Who Will Pay for Your Advice": "Russell Brunson, Robert T. Kiyosaki - foreword",
  "Extreme Ownership: How U.S. Navy SEALs Lead and Win": "Jocko Willink, Leif Babin",
  "F--k Your Feelings: Master Your Mind, Accomplish Anything and Become a More Significant Human": "Ryan Munsey",
  "F.U. Money: Make As Much Money As You Damn Well Want And Live Your LIfe As You Damn Well Please!": "Dan Lok",
  "Faith Affirmations: Positive Daily Affirmations to Strengthen Your Beliefs on Things Seen and Unseen Using the Law of Attraction": "Stephens Hyang",
  "Faith Driven Entrepreneur: What It Takes to Step Into Your Purpose and Pursue Your God-Given Call to Create": "Henry Kaestner, J.D. Greear, Chip Ingram",
  "Faith Finances: A Guide to Mastering the Three Biblical Principles of Financial Success in Eight Steps": "Thomas E. Zordani",
  "Faith of My Fathers": "John McCain, Mark Salter",
  "Fast This Way: Burn Fat, Heal Inflammation, and Eat like the High-Performing Human You Were Meant to Be": "Dave Asprey",
  "Fasting": "Jentezen Franklin",
  "Fault Lines: The Social Justice Movement and Evangelicalism's Looming Catastrophe": "Voddie T. Baucham",
  "Fervent: A Woman's Battle Plan to Serious, Specific and Strategic Prayer": "Priscilla Shirer",
  "Financial Freedom: A Proven Path to All the Money You Will Ever Need": "Grant Sabatier, Vicki Robin - introduction",
  "Finding Your Best: A Conversation on High Performance Mindset: Insights From Sport for Everyday Living": "Dr. Michael Gervais, Pete Carroll",
  "Finding Your Purpose": "Christine Whelan",
  "Fish Out of Water: A Search for the Meaning of Life: A Memoir": "Eric Metaxas",
  "Flow: Living at the Peak of Your Abilities": "Mihaly Csikszentmihalyi Ph.D.",
  "Follow Me to Freedom: Leading as an Ordinary Radical": "John Perkins, Shane Claiborne",
  "Following Jesus: Finding Our Way Home in an Age of Anxiety": "Henri J. M. Nouwen, Richard Rohr - introduction, Gabrielle Earnshaw - editor",
  "Folsom Untold: The Strange True Story of Johnny Cash's Greatest Album: An Audible Original Drama": "Danny Robins",
  "For the Body: Recovering a Theology of Gender, Sexuality, and the Human Body": "Timothy C. Tennent, Ajith Fernando - introduction",
  "Fresh Air": "Terry Gross",
  "Furious Longing of God": "Brennan Manning",
  "Gateway to Success and Happiness": "Og Mandino",
  "Get Off Your \"But\": How to End Self-Sabotage and Stand Up for Yourself": "Sean Stephenson",
  "Get Out of Your Own Way: How to Overcome Any Obstacle in Your Life": "Larry Winget",
  "Getting Everything You Can Out of All You've Got: 21 Ways You Can Out-Think, Out-Perform, and Out-Earn the Competition": "Jay Abraham",
  "Getting to Know Jesus": "George MacDonald",
  "Gift of the Red Bird: The Story of a Divine Encounter": "Paula D'Arcy",
  "Give and Take: A Revolutionary Approach to Success": "Adam Grant",
  "Giving It All Away\u2026and Getting It All Back Again: The Way of Living Generously": "David Green, Bill High",
  "Goals: Questions and Answers": "Bob Proctor",
  "God Wants You to Be Rich: The Christian Guide to Financial Freedom & Unlimited Wealth (12 Steps to Bring More Money into Your Life While Still Serving the Lord)": "Alex Landon",
  "God in the Dock: Essays on Theology and Ethics": "C. S. Lewis",
  "Good and Beautiful Community: Following the Spirit, Extending Grace, Demonstrating Love (Apprentice Series, Book 3)": "James Bryan Smith",
  "Good and Beautiful God: Falling in Love With the God Jesus Knows": "James Bryan Smith",
  "Good to Great: Why Some Companies Make the Leap...And Others Don't": "Jim Collins",
  "Gospel of Jesus": "Daniel L. Johnson",
  "Grain Brain: The Surprising Truth about Wheat, Carbs, and Sugar (Your Brain's Silent Killers) by David Perlmutter -- Summary, Review & Analysis": "Save Time Summaries",
  "Great by Choice: Uncertainty, Chaos, and Luck--Why Some Thrive Despite Them All": "Jim Collins, Morten T. Hansen",
  "Greater: Dream bigger. Start smaller. Ignite God's Vision for Your Life": "Steven Furtick",
  "Grit: The Power of Passion and Perseverance": "Angela Duckworth",
  "Grow Rich with the Power of Your Subconscious Mind": "Joseph Murphy",
  "Habit 4 Think Win-Win: The Habit of Mutual Benefit": "Stephen R. Covey",
  "Habits For Good Sleep: 10 Steps for a Great Sleep and a Happier Life": "Dr Tim Sharp, Audible Sleep",
  "Halftime: Moving from Success to Significance": "Bob P. Buford, \"An Invigorating Challenge\" Jim Collins Author of Good to Great - introduction",
  "Happiness Is a Serious Problem: A Human Nature Repair Manual": "Dennis Prager",
  "Harmonic Wealth: The Secret of Attracting the Life You Want": "James Arthur Ray",
  "Head in the Cloud: Why Knowing Things Still Matters When Facts Are So Easy to Look Up": "William Poundstone",
  "Healing Back Pain: The Mind-Body Connection": "John E. Sarno M.D.",
  "Hearing God: Developing a Conversational Relationship with God": "Dallas Willard",
  "Heaven": "Randy Alcorn",
  "Help, Thanks, Wow: The Three Essential Prayers": "Anne Lamott",
  "Hero on a Mission: A Path to a Meaningful Life": "Donald Miller",
  "His Needs, Her Needs: Building an Affair-Proof Marriage": "Willard Harley",
  "History Speaks, Volume 2": "Andrew Carnegie, Thomas Edison, William Howard Taft, O. Henry, Theodore Roosevelt",
  "Hold Me Tight: Seven Conversations for a Lifetime of Love": "Dr. Sue Johnson",
  "Homeless to Billionaire: The 18 Principles of Wealth Attraction and Creating Unlimited Opportunity": "Andres Pira, Dr. Joe Vitale - collaborator",
  "Hook Point: How to Stand Out in a 3-Second World": "Brendan Kane",
  "How Are You, Really?: Living Your Truth One Answer at a Time": "Jenna Kutcher",
  "How Do You Kill 11 Million People?: Why the Truth Matters More Than You Think": "Andy Andrews",
  "How God Became King: The Forgotten Story of the Gospels": "N. T. Wright",
  "How Good Is Good Enough?": "Andy Stanley",
  "How I Raised Myself From Failure to Success in Selling": "Frank Bettger",
  "How to Completely Change Your Life in 30 Seconds": "Earl Nightingale",
  "How to Get Paid for What You Know: Turning Your Knowledge, Passion, and Experience into an Online Income Stream in Your Spare Time": "Graham Cochrane",
  "How to Get and Stay Motivated": "Grant Cardone",
  "How to Know a Person: The Art of Seeing Others Deeply and Being Deeply Seen": "David Brooks",
  "How to Own Your Own Mind": "Napoleon Hill, Don Green - introduction",
  "How to Say It: Words That Make a Difference": "Allison Friederichs Atkison, The Great Courses",
  "How to Stay Motivated: Developing the Qualities of Success": "Zig Ziglar",
  "How to Stop Worrying and Start Living: Time-Tested Methods for Conquering Worry": "Dale Carnegie, Donna Dale Carnegie - introduction",
  "How to Talk to Anybody, Anytime, Anywhere: 3 Steps to Make Instant Connections": "Chris Widener",
  "How to Train Your Mind: Exploring the Productivity Benefits of Meditation": "Chris Bailey",
  "How to Win Friends & Influence People": "Dale Carnegie",
  "How to Win at the Sport of Business: If I Can Do It, You Can Do It": "Mark Cuban",
  "How to Write, Publish, and Market a Book with No Out-of-Pocket Expense": "Rebecca Morgan",
  "I Will Teach You to Be Rich: No Guilt. No Excuses. No B.S. Just a 6-Week Program That Works (Second Edition)": "Ramit Sethi",
  "INSTINCT Daily Readings: The Power to Unleash Your Inborn Drive": "T.D. Jakes",
  "If God Is Good: Faith in the Midst of Suffering and Evil": "Randy Alcorn",
  "If You're Not First, You're Last: Sales Strategies to Dominate Your Market and Beat Your Competition": "Grant Cardone",
  "Imagination Creates Reality: Neville Goddard Lectures": "Neville Goddard",
  "Imagine Big: Unlock the Secret to Living Out Your Dreams": "Terri Savelle Foy",
  "Imagine Heaven: Near-Death Experiences, God's Promises, and the Exhilarating Future That Awaits You": "John Burke",
  "Immortal Diamond: The Search for Our True Self": "Richard Rohr",
  "Increased Brain Function: More Creativity & Intelligence with Subliminal Brain Power": "Josh Pace",
  "Indistractable: How to Control Your Attention and Choose Your Life": "Nir Eyal, Julie Li",
  "Influence: 47 Forbidden Psychological Tactics You Can Use To Motivate, Influence and Persuade Your Prospect": "Dan Lok",
  "Influencer: The Power to Change Anything": "Kerry Patterson, Joseph Grenny, David Maxfield",
  "Innovation and Entrepreneurship": "Peter F. Drucker",
  "Insanely Simple: The Obsession that Drives Apple's Success": "Ken Segall",
  "Inspired: The Secrets of Bob Proctor": "Linda Proctor",
  "Integrity: The Courage to Meet the Demands of Reali": "Henry Cloud",
  "Internal Time: Chronotypes, Social Jet Lag, and Why You're So Tired": "Till Roenneberg",
  "Interview with Jack Canfield": "Jack Canfield",
  "Into the Light: Real Life Stories About Angelic Visits, Visions of the Afterlife, and Other Pre-Death Experiences": "John Lerma",
  "Invitation to Retreat: The Gift and Necessity of Time Away with God": "Ruth Haley Barton",
  "Invitation to Solitude and Silence: Experiencing God's Transforming Presence": "Ruth Haley Barton",
  "Invitation to a Journey: A Road Map for Spiritual Formation": "M. Robert Mulholland Jr.",
  "It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle": "Mark Wolynn",
  "It's Not About the Money": "Bob Proctor",
  "It's OK That You're Not OK: Meeting Grief and Loss in a Culture That Doesn't Understand": "LPC Megan Devine, Mark Nepo - introduction",
  "It's You": "Les Brown",
  "It's Your Time: Activate Your Faith, Accomplish Your Dreams, and Increase in God's Favor": "Joel Osteen",
  "Jesus Unbound: Liberating the Word of God from the Bible": "Keith Giles",
  "Jesus, Continued...: Why the Spirit Inside You Is Better than Jesus Beside You": "J.D. Greear",
  "Jocko Willink: A Biography": "Matt Freeman",
  "Jump: Take the Leap of Faith to Achieve Your Life of Abundance": "Steve Harvey",
  "Just Jones: Sometimes a Thing Is Impossible . . . Until It Is Actually Done (A Noticer Book)": "Andy Andrews",
  "Just Listen: Discover the Secret to Getting Through to Absolutely Anyone": "Mark Goulston",
  "Just Walk Across the Room": "Bill Hybels",
  "Killing Lincoln: The Shocking Assassination that Changed America Forever": "Bill O'Reilly, Martin Dugard",
  "Killing Sacred Cows: Overcoming the Financial Myths That Are Destroying Your Prosperity": "Garrett B. Gunderson",
  "King's Cross: The Story of the World in the Life of Jesus": "Timothy Keller",
  "Law of Abundance": "Jack Canfield",
  "Law of Attraction to Make More Money: 12 Hidden Truths to Help You Shift Your Mindset and Start Attracting the Abundance You Deserve, Without Trying so Hard, Book 5": "Elena G. Rivers",
  "Lead Yourself First": "Raymond M. Kethledge, Michael S. Erwin",
  "Leaders Eat Last: Why Some Teams Pull Together and Others Don't": "Simon Sinek",
  "Leadership Lessons of Steve Jobs (Harvard Business Review)": "Walter Isaacson",
  "Leadership by the Book: Tools to Transform Your Workplace": "Kenneth Blanchard, Bill Hybels, Phil Hodges",
  "Leap First: Creating Work That Matters": "Seth Godin",
  "Learned Optimism: How to Change Your Mind and Your Life": "Martin E. P. Seligman",
  "Learning from the Light: Pre-Death Experiences, Prophecies, and Angelic Messages of Hope": "John Lerma",
  "Les Brown - How Passion Leads to a Bigger Life: Conversations with the Best Entrepreneurs on the Planet": "Les Brown",
  "Let It Go: Forgive So You Can Be Forgiven": "T.D. Jakes",
  "Let Your Life Speak: Listening for the Voice of Vocation": "Parker J. Palmer",
  "Letters to the Church": "Francis Chan",
  "Lies We Believe About God": "Wm. Paul Young, C. Baxter Kruger - introduction",
  "Life Force: How New Breakthroughs in Precision Medicine Can Transform the Quality of Your Life & Those You Love": "Tony Robbins, Peter H. Diamandis, Robert Hariri",
  "Life Without Limits: Inspiration for a Ridiculously Good Life": "Nick Vujicic",
  "Life after Life: The Investigation of a Phenomenon - Survival of Bodily Death": "Raymond A. Moody Jr.",
  "Life of the Beloved: Spiritual Living in a Secular World": "Henri J. M. Nouwen",
  "Linchpin: Are You Indispensable?": "Seth Godin",
  "Live Your Truth and Other Lies: Exposing Popular Deceptions That Make Us Anxious, Exhausted, and Self-Obsessed": "Alisa Childers",
  "Living Your Dreams: Your Personal Success Program": "Mark Victor Hansen",
  "Living a Laptop Lifestyle: Reclaim Your Life by Making Money Online": "Greg Scott, Fiona Scott",
  "Living in a Mindful Universe: A Neurosurgeon's Journey into the Heart of Consciousness": "Eben Alexander MD, Karen Newell",
  "Love Does: Discover a Secretly Incredible Life in an Ordinary World": "Bob Goff",
  "Love Lives Here: Finding What You Need in a World Telling You What You Want": "Maria Goff, Bob Goff - foreword",
  "Love Your Enemies: How Decent People Can Save America from the Culture of Contempt": "Arthur C. Brooks",
  "Make Miracles in Forty Days: Turning What You Have into What You Want": "Melody Beattie",
  "Making Vision Stick": "Andy Stanley",
  "Man Up!: Becoming a Godly Man in an Ungodly World": "Jody Burkeen",
  "Man's Search for Meaning: An Introduction to Logotherapy": "Viktor E. Frankl",
  "Managing Oneself": "Peter F. Drucker",
  "Mandela's Way: Fifteen Lessons on Life, Love, and Courage": "Richard Stengel",
  "Market Mind Games: A Radical Psychology of Investing, Trading, and Risk": "Denise Shull",
  "Master Storytelling: How to Turn Your Experiences into Stories that Teach, Lead, and Inspire": "Mark Carpenter, Darrell Harmon",
  "Master of One: Find and Focus on the Work You Were Created to Do": "Jordan Raynor",
  "Mastering the Seven Decisions: That Determine Personal Success": "Andy Andrews",
  "Mastery": "Robert Greene",
  "Measure of a Man: Twenty Attributes of a Godly Man": "Gene Getz",
  "Meister Eckhart's Book of Secrets: Meditations on Letting Go and Finding True Freedom": "Jon M. Sweeney, Mark S. Burrows",
  "Mere Christianity": "C. S. Lewis",
  "Million Dollar Identity: Experts, CEOs, and Entrepreneurs Share How to Build, Monetize, and Scale Your Market Authority, Profit, and Influence for 7+ Figure Success": "Jamie Wolf, Myron Golden, Victoria Kennedy, Dan Ashburn, Eric Beer, Angela Little",
  "Million Dollar Method: Grow Your Influence Audience & Revenue Fast! (Million Dollar Story, Book 5)": "Jamie Wolf",
  "Million Dollar Weekend: The Surprisingly Simple Way to Launch a 7-Figure Business in 48 Hours": "Noah Kagan, Tahl Raz",
  "Mindfulness: The Most Effective Techniques: Connect With Your Inner Self To Reach Your Goals Easily and Peacefully": "Ian Tuhovsky",
  "Mindset: The New Psychology of Success": "Carol Dweck",
  "Miracle Morning Millionaires: What the Wealthy Do Before 8AM That Will Make You Rich (The Miracle Morning)": "Hal Elrod, David Osborn, Honoree Corder",
  "Miracles: What They Are, Why They Happen, and How They Can Change Your Life": "Eric Metaxas",
  "Mirror for the Soul: A Christian Guide to the Enneagram": "Alice Fryling",
  "Misreading Scripture with Western Eyes: Removing Cultural Blinders to Better Understand the Bible": "Brandon J. O'Brien, E. Randolph Richards",
  "Molecules of Emotion: Why You Feel the Way You Feel": "Candace B. Pert Ph.D. Ph.D.",
  "Money, and the Law of Attraction: Learning to Attract Wealth, Health, and Happiness": "Esther Hicks",
  "Money: Master the Game: 7 Simple Steps to Financial Freedom": "Tony Robbins",
  "More Important Than Money": "Robert T. Kiyosaki",
  "Mostly What God Does: Reflections on Seeking and Finding His Love Everywhere": "Savannah Guthrie",
  "Mother Teresa: Come Be My Light: The Private Writings of the 'Saint of Calcutta'": "Brian Kolodiejchuk M.C.",
  "Motivation to Succeed\\\\!: The Psychology of Motivation": "Made for Success, Zig Ziglar, Les Brown, Mark Victor Hansen",
  "Multiple Sources of Income - Positive Expectations": "Bob Proctor",
  "Napoleon Hill - The Road to Riches: 13 Keys to Success": "Napoleon Hill, Greg S. Reid",
  "Napoleon Hill in His Own Voice: Rare Recordings of His Lectures": "Napoleon Hill",
  "Napoleon Hill's Golden Rules: The Lost Writings": "Napoleon Hill",
  "Napoleon Hill's Keys to Positive Thinking: 10 Steps to Health, Wealth, and Success": "Michael J. Ritt Jr., Napoleon Hill",
  "Necessary Endings: The Employees, Businesses, and Relationships That All of Us Have to Give Up in Order to Move Forward": "Henry Cloud",
  "Negative Self-Talk and How to Change It": "Shad Helmstetter PhD",
  "NeuroWisdom: The New Brain Science of Money, Happiness, and Success": "Mark Robert Waldman, Chris Manning PhD",
  "Never Enough: From Barista to Billionaire": "Andrew Wilkinson",
  "Never Split the Difference: Negotiating as if Your Life Depended on It": "Chris Voss, Tahl Raz",
  "Nikola Tesla: A Captivating Guide to the Life of a Genius Inventor": "Captivating History",
  "Nine-Figure Mindset: How to Go from Zero to Over $100 Million in Net Worth": "Brandon Dawson",
  "No Boundaries": "Les Brown",
  "No Excuses\\\\!: The Power of Self-Discipline for Success in Your Life": "Brian Tracy",
  "Not Being Bothered: Increasing Your Achievement During Distracting Times": "Dan Sullivan",
  "Not God Enough: Why Your Small God Leads to Big Problems": "J. D. Greear, Dr. David Jeremiah - Foreword",
  "Nudge: Awakening Each Other to the God Who's Already There": "Leonard Sweet",
  "On Earth as in Heaven: Daily Wisdom for Twenty-First Century Christians": "N. T. Wright",
  "One Up On Wall Street: How To Use What You Already Know To Make Money In The Market": "Peter Lynch",
  "Opening Up by Writing It Down, Third Edition: How Expressive Writing Improves Health and Eases Emotional Pain": "James W. Pennebaker, Joshua M. Smyth",
  "Organic Church: Growing Faith Where Life Happens": "Neil Cole",
  "Outliers: The Story of Success": "Malcolm Gladwell",
  "Paranormal: My Life in Pursuit of the Afterlife": "Raymond Moody MD, Paul Perry",
  "Pathways to Peace of Mind": "Napoleon Hill, Don Green - foreword, Dr. J.B. Hill - introduction",
  "Peace Is Every Step: The Path of Mindfulness in Everyday Life": "Thich Nhat Hanh",
  "Pep Talk: Learn the Language of Success Through Positive Declarations": "Terri Savelle Foy",
  "Personality Isn't Permanent: Break Free from Self-Limiting Beliefs and Rewrite Your Story": "Benjamin Hardy",
  "Pitch Anything: An Innovative Method for Presenting, Persuading, and Winning the Deal": "Oren Klaff",
  "Platform: Get Noticed in a Noisy World": "Michael Hyatt",
  "Poke the Box": "Seth Godin",
  "Poverty, Riches, and Wealth: Moving from a Life of Lack into True Kingdom Abundance": "Kris Vallotton",
  "Powerful Listening: How to Harness Your Most Essential Skill": "Kwame Christian, The Great Courses",
  "Practical AI for Beginners: Unlock the Power of Artificial Intelligence with Simple Tools to Boost Productivity, Save Time, and Make Smarter Decisions in Everyday Life": "Paco Barker",
  "Practicing Mindfulness: An Introduction to Meditation": "Mark W. Muesse, The Great Courses",
  "Pray First: The Transformative Power of a Life Built on Prayer": "Chris Hodges",
  "Preaching: Communicating Faith in an Age of Skepticism": "Timothy Keller",
  "Principles: Life and Work": "Ray Dalio",
  "Procrastinate on Purpose: 5 Permissions to Multiply Your Time": "Rory Vaden",
  "Procrastination: The Ultimate Guide to Mastering Difficult Tasks, Breaking the Procrastination Habit and Increase Willpower to Achieve Your Goals": "Dan Kiyosaki",
  "Proof of Life after Life: 7 Reasons to Believe There Is an Afterlife": "Raymond Moody Jr. M.D. Ph.D. M.D. Ph.D., Paul Perry, Raymond Moody - introduction Jr. M.D. Ph.D. M.D. Ph.D.",
  "Pursuit of the Magnificent": "Deepak Chopra M.D., John F. Demartini",
  "Quantum: Einstein, Bohr, and the Great Debate about the Nature of Reality": "Manjit Kumar",
  "Quiet: The Power of Introverts in a World That Can't Stop Talking": "Susan Cain",
  "Rabbi Daniel Lapin Show": "Talk 4 Radio",
  "Radical: Taking Back Your Faith From the American Dream": "David Platt",
  "Raise Your Frequency and Increase Your Vibration Visualization: Powerful Daily Visualization Hypnosis to Condition Your Subconscious Mind to Achieve the Ultimate Success": "Will Johnson Jr.",
  "Ready, Fire, Aim: Zero to $100 Million in No Time Flat": "Michael Masterson",
  "Real Magic: Making Miracles in All Areas of Your Life": "Dr. Wayne W. Dyer",
  "Redeeming Your Time: 7 Biblical Principles for Being Purposeful, Present, and Wildly Productive": "Jordan Raynor",
  "Reflections on the Psalms": "C. S. Lewis",
  "Reinvention: How to Make the Rest of Your Life the Best of Your Life": "Brian Tracy",
  "Relentless: From Good to Great to Unstoppable": "Tim S. Grover",
  "Reposition Yourself: Living Life Without Limits": "T.D. Jakes",
  "Resilience Scores Goals": "Bob Proctor",
  "Rich Dad Advisors: Tax-Free Wealth: How to Build Massive Wealth by Permanently Lowering Your Taxes": "Tom Wheelwright CPA",
  "Rich Dad Poor Dad: What the Rich Teach Their Kids About Money - That the Poor and Middle Class Do Not!": "Robert T. Kiyosaki",
  "Rich Dad's Cashflow Quadrant: Guide to Financial Freedom": "Robert T. Kiyosaki",
  "Rich20Something: Ditch Your Average Job, Start an Epic Business, and Score the Life You Want": "Daniel DiPiazza",
  "Rip-Roaring Wealth": "Mark Victor Hansen, Made for Success",
  "Rising Strong: How the Ability to Reset Transforms the Way We Live, Love, Parent, and Lead": "Bren\u00e9 Brown",
  "Rule #1: The Simple Strategy for Successful Investing - in Only 15 Minutes a Week!": "Phil Town",
  "Run with the Horses: The Quest for Life at its Best": "Eugene Peterson",
  "Saban: The Making of a Coach": "Monte Burke",
  "Sacred Pace: Four Steps to Hearing God and Aligning Yourself With His Will": "Terry Looper, Kris Bearss",
  "Sacred Pathways: Discover Your Soul's Path to God": "Gary Thomas",
  "Sacred Rhythms: Arranging Our Lives for Spiritual Transformation": "Ruth Haley Barton",
  "Same Kind of Different as Me": "Ron Hall, Denver Moore, Lynn Vincent",
  "Scientific Advertising": "Claude Hopkins",
  "Scott and Amundsen: Their Race to the South Pole": "Roland Huntford",
  "Scripture and the Authority of God: How to Read the Bible Today": "N.T. Wright",
  "Secrets of Self-Made Millionaires (Live)": "Brian Tracy",
  "Secrets of Selling": "Grant Cardone",
  "Secrets of the Millionaire Mind: Mastering the Inner Game of Wealth": "T. Harv Eker",
  "Seeking Allah, Finding Jesus: Third Edition with Bonus Content, New Reflections": "Nabeel Qureshi, Lee Strobel - introduction",
  "Self Reliance": "Ralph Waldo Emerson",
  "Self-Reliance and Other Essays (AmazonClassics Edition)": "Ralph Waldo Emerson",
  "Sell or Be Sold: How to Get Your Way in Business and in Life": "Grant Cardone",
  "Selling You!: A Personal Guide to Achieving The Most By Becoming Your Best": "Napoleon Hill",
  "Series 65 Exam Prep: An Entertaining Guide: Learn Economic Factors, Investment Vehicle Characteristics, Client Investment Recommendations, and Laws and Regulations through Storytelling": "Maxwell Pepper",
  "Shrink: Faithful Ministry in a Church-Growth Culture": "Scot McKnight, Tim Suttle",
  "Simple Abundance: Living by Your Own Lights": "Sarah Ban Breathnach",
  "Simply Jesus: A New Vision of Who He Was, What He Did, and Why He Matters": "N. T. Wright",
  "Small Faith, Great God": "N.T. Wright",
  "So Good They Can't Ignore You: Why Skills Trump Passion in the Quest for Work You Love": "Cal Newport",
  "Someday Is Today: 22 Simple, Actionable Ways to Propel Your Creative Life": "Matthew Dicks",
  "Something Needs to Change: An Urgent Call to Make Your Life Count": "David Platt",
  "Sorry for Your Loss": "Michael Cruz Kayne",
  "Soulprint: Discovering Your Divine Destiny": "Mark Batterson",
  "Spark: The Revolutionary New Science of Exercise and the Brain": "John J. Ratey MD, Eric Hagerman",
  "Spiritual Economics": "Eric Butterworth",
  "Spiritual Formation: Following the Movements of the Spirit": "Henri J. M. Nouwen",
  "Spiritual Liberation: Fulfilling Your Soul's Potential": "Michael Bernard Beckwith",
  "Spiritual Principles": "Marianne Williamson",
  "Stars at Night: When Darkness Unfolds as Light": "Paula D'Arcy",
  "Start with Why: How Great Leaders Inspire Everyone to Take Action": "Simon Sinek",
  "Step Into Your Greatness (Live)": "Les Brown",
  "Step of Faith: A Novel": "Richard Paul Evans",
  "Sterling Biographies: Abraham Lincoln: From Pioneer to President": "Ellen Blue Phillips",
  "Sterling Biographies: Albert Einstein: The Miracle": "Tabatha Yeatts",
  "Sterling Biographies: Benjamin Franklin": "Maria Mihalik Higgins",
  "Steve Jobs: The Man Who Thought Different: A Biography": "Karen Blumenthal",
  "Stillness Is the Key": "Ryan Holiday",
  "Stillness Speaks: Stillness amidst the World": "Eckhart Tolle",
  "Stock Market Investing Basics Explained": "Can Akdeniz",
  "Stop Acting Rich: And Start Living Like a Real Millionaire": "Thomas J. Stanley",
  "Stories Sell: Storyworthy Strategies to Grow Your Business and Brand": "Matthew Dicks, Masha Cresalia - foreword",
  "Stories That Stick: How Storytelling Can Captivate Customers, Influence Audiences, and Transform Your Business": "Kindra Hall",
  "Storyworthy: Engage, Teach, Persuade, and Change Your Life Through the Power of Storytelling": "Matthew Dicks, Dan Kennedy - foreword",
  "Succeeding Against the Odds: The Autobiography of a Great American Businessman": "John H. Johnson, Lerone Bennett Jr.",
  "Success Built to Last: Creating a Life That Matters (Live)": "Stewart Emery, Mark Thompson",
  "Success Built to Last: Creating a Life that Matters": "Jerry Porras, Stewart Emery, Mark Thompson",
  "Success Through a Positive Mental Attitude": "Napoleon Hill",
  "Suffering Is Never for Nothing": "Elisabeth Elliott",
  "Summary and Analysis of 12 Rules for Life: An Antidote to Chaos by Jordan B. Peterson: Book Tigers Self Help and Success Summaries, Book 12": "Book Tigers",
  "Summary of Never Split the Difference: Negotiating as if Your Life Depended on It by Chris Voss with Tahl Raz: Key Takeaways & Analysis Included": "Ninja Reads",
  "Sun Stand Still: What Happens When You Dare to Ask God for the Impossible": "Steven Furtick",
  "Super Rich: A Guide to Having It All": "Russell Simmons, Chris Morrow",
  "Surprised by Joy: The Shape of My Early Life": "C. S. Lewis",
  "Survival is not Enough: Zooming, Evolution, and the Future of Your Company": "Seth Godin",
  "Switch: How to Change Things When Change Is Hard": "Chip Heath, Dan Heath",
  "TED Talk Secrets: Storytelling and Presentation Design for Delivering Great TED Style Talks": "Jacob Andrews",
  "TED Talks Storytelling: 23 Storytelling Techniques from the Best TED Talks": "Akash Karia",
  "Take the Stairs: 7 Steps to Achieving True Success": "Rory Vaden",
  "Talking to Strangers: What We Should Know about the People We Don't Know": "Malcolm Gladwell",
  "Taming the Tiger Within": "Thich Nhat Hanh, Pritam Singh",
  "Tapping the Source: Using the Master Key System for Abundance and Happiness": "John Selby, Richard Greninger, William Gladstone, Jack Canfield, Mark Victor Hansen",
  "Teach Us to Pray": "Gordon T. Smith",
  "The $100 Startup: Reinvent the Way You Make a Living, Do What You Love, and Create a New Future": "Chris Guillebeau",
  "The 10 Stories Great Leaders Tell": "Paul Smith",
  "The 15 Commitments of Conscious Leadership: A New Paradigm for Sustainable Success": "Jim Dethmer, Diana Chapman, Kaley Klemp",
  "The 25-Year Framework: Your 21st-Century Entrepreneurial Mindset for Continually Slowing Down Time While Speeding Up Your Progress Over a 25-Year Period": "Dan Sullivan",
  "The 3-Day Effect": "Florence Williams",
  "The 38 Letters from J.D. Rockefeller to His Son: Perspectives, Ideology, and Wisdom": "J. D. Rockefeller",
  "The 4 C's Formula: Your Building Blocks of Growth: Commitment, Courage, Capability, and Confidence.": "Dan Sullivan",
  "The 4-Hour Body: An Uncommon Guide to Rapid Fat-Loss, Incredible Sex, and Becoming Superhuman": "Timothy Ferriss",
  "The 4-Hour Workweek: Escape 9-5, Live Anywhere, and Join the New Rich (Expanded and Updated)": "Timothy Ferriss",
  "The 6 Habits of Growth": "Brendon Burchard",
  "The 7 Principles of Public Speaking: Proven Methods from a PR Professional": "Richard Zeoli",
  "The 9 Types of Leadership: Mastering the Art of People in the 21st Century Workplace": "Beatrice Chestnut PhD",
  "The ABC Model Breakthrough: Shifting Your Time into Activities That Fascinate and Motivate You": "Dan Sullivan",
  "The ABCs of Success: The Essential Principles from America's Greatest Prosperity Teacher": "Bob Proctor, Sandra Gallagher - introduction",
  "The Ai-Driven Leader: Harnessing AI to Make Faster, Smarter Decisions": "Geoff Woods",
  "The Aladdin Factor: How to Ask for and Get What You Want in Every Area of Your Life": "Mark Victor Hansen, Jack Canfield",
  "The Amen Solution: The Brain Healthy Way to Lose Weight and Keep It Off": "Daniel G. Amen M.D.",
  "The Art of Exceptional Living": "Jim Rohn",
  "The Art of Happiness: A Handbook for Living": "His Holiness the Dalai Lama, Howard C. Cutler M.D.",
  "The Art of Learning: An Inner Journey to Optimal Performance": "Josh Waitzkin",
  "The Art of Less Doing": "Ari Meisel",
  "The Art of Living": "Bob Proctor, Sandra Gallagher",
  "The Art of Mental Training: A Guide to Performance Excellence, Collector's Edition": "D. C. Gonzalez",
  "The Art of Procrastination: A Guide to Effective Dawdling, Lollygagging, and Postponing, or, Getting Things Done by Putting Them Off": "John Perry",
  "The Art of Public Speaking": "Dale Carnegie, J. Berg Esenwein - preface",
  "The Art of Seduction: An Indispensible Primer on the Ultimate Form of Power": "Robert Greene",
  "The Art of Storytelling: Easy Steps to Presenting an Unforgettable Story": "John D. Walsh",
  "The Art of Storytelling: From Parents to Professionals": "Hannah B. Harvey, The Great Courses",
  "The Art of War": "Sun Tzu",
  "The Artist's Way: A Spiritual Path to Higher Creativity": "Julia Cameron",
  "The Attributes of God": "Arthur W. Pink",
  "The Autobiography of Benjamin Franklin": "Benjamin Franklin",
  "The Autobiography of Martin Luther King, Jr.": "Clayborne Carson",
  "The Automatic Millionaire: A Powerful One-Step Plan to Live and Finish Rich": "David Bach",
  "The Bottom of the Pool: Thinking Beyond Your Boundaries to Achieve Extraordinary Results": "Andy Andrews",
  "The Challenge of Acts: Rediscovering What the Church Was and Is": "N. T. Wright",
  "The Chosen": "Chaim Potok",
  "The Christian Atheist: Believing in God but Living As If He Doesn't Exist": "Craig Groeschel",
  "The Circle Maker: Praying Circles Around Your Biggest Dreams and Greatest Fears": "Mark Batterson",
  "The Claude Cowork Handbook (Revised & Expanded Spring 2026): Your Complete Guide to Getting Started and Getting More Done": "John Collins",
  "The Coming Jobs War": "Jim Clifton",
  "The Complete Guide to Fasting: Heal Your Body Through Intermittent, Alternate-Day, and Extended Fasting": "Jimmy Moore, Dr. Jason Fung",
  "The Complete Guide to Vision Boards: The Ultimate Starter Kit to Get Wildly Clear and Create the Life of Your Dreams": "Christine Kane",
  "The Complete Wallace D. Wattles Collection": "Wallace D. Wattles",
  "The Compound Effect: Multiply Your Success One Simple Step at a Time": "Darren Hardy",
  "The Confidence Gap: A Guide to Overcoming Fear and Self-Doubt": "Russ Harris, Steven Hayes PhD - foreword",
  "The Courage to Teach: Exploring the Inner Landscape of a Teacher's Life": "Parker J. Palmer",
  "The Craving Mind: From Cigarettes to Smartphones to Love - Why We Get Hooked and How We Can Break Bad Habits": "Judson Brewer, Jon Kabat-Zinn - foreward",
  "The Daniel Plan: 40 Days to a Healthier Life": "Rick Warren D.Min., Daniel Amen M.D., Mark Hyman M.D.",
  "The Day That Turns Your Life Around": "Jim Rohn",
  "The Decision: Overcoming Today's BS for Tomorrow's Success": "Kevin Hart",
  "The Deep Learning Revolution": "Terrence J. Sejnowski",
  "The Divine Conspiracy: Rediscovering Our Hidden Life in God": "Dallas Willard",
  "The Edinburgh Lectures on Mental Science": "Thomas Troward",
  "The Element: How Finding Your Passion Changes Everything": "Ken Robinson Ph.D.",
  "The Emotionally Healthy Leader: How Transforming Your Inner Life Will Deeply Transform Your Church, Team, and the World": "Peter Scazzero",
  "The Entrepreneur's Edge: Turning Purpose into Profit and Fulfillment": "Dan Sullivan, Joe Polish",
  "The Face on the Milk Carton": "Caroline B. Cooney",
  "The Final Summit: A Quest to Find the One Principle That Will Save Humanity": "Andy Andrews",
  "The First Billion Is the Hardest: Reflections on a Life of Comebacks and America's Energy Future": "T. Boone Pickens",
  "The Five Dysfunctions of a Team: A Leadership Fable": "Patrick Lencioni",
  "The Five Most Important Questions: You Will Ever Ask About Your Organization": "Peter F. Drucker",
  "The Founding Fathers on Leadership: Classic Teamwork in Changing Times": "Donald T. Phillips",
  "The Four Obsessions of an Extraordinary Executive: A Leadership Fable": "Patrick Lencioni, Patrick Lencioni - introduction",
  "The Freedom of Self-Forgetfulness: The Path to True Christian Joy": "Timothy Keller",
  "The G-Code: A Modern Day Code for Spiritual Enlightenment, Spiritual Growth and Personal Development": "Cochise Tarak-Saa",
  "The Gap and the Gain: The High Achievers' Guide to Happiness, Confidence, and Success": "Dan Sullivan, Benjamin Hardy",
  "The Generosity Factor: Discover the Joy of Giving Your Time, Talent, and Treasure": "Ken Blanchard, S.Truett Cathy",
  "The Genie Within: Your Subconscious Mind - How It Works and How to Use It": "Harry W. Carpenter",
  "The Gifts of Imperfection: Let Go of Who You Think You're Supposed to Be and Embrace Who You Are": "Bren\u00e9 Brown",
  "The Good and Beautiful Life: Putting on the Character of Christ": "James Bryan Smith",
  "The Grace of God": "Andy Stanley",
  "The Gratitude Effect": "John F. DeMartini",
  "The Great Sex Rescue: The Lies You've Been Taught and How to Recover What God Intended": "Sheila Wray Gregoire, Rebecca Gregoire Lindenbach, Joanna Sawatsky",
  "The Greatest Generation Speaks: Letters and Reflections": "Tom Brokaw",
  "The Greatest Mystery in the World": "Og Mandino",
  "The Greatest Salesman in the World": "Og Mandino",
  "The Happiness Advantage: The Seven Principles of Positive Psychology That Fuel Success and Performance at Work": "Shawn Achor",
  "The Happiness Hypothesis: Finding Modern Truth in Ancient Wisdom": "Jonathan Haidt",
  "The Heart Mender: A Story of Second Chances": "Andy Andrews",
  "The Hero with a Thousand Faces: The Collected Works of Joseph Campbell": "Joseph Campbell",
  "The Hero's 2 Journeys": "Michael Hauge, Christopher Vogler",
  "The Hole in Our Gospel: The Answer That Changed My Life and Might Just Change the World": "Richard Stearns",
  "The Hundred Story Home: A Memoir of Finding Faith in Ourselves and Something Bigger": "Kathy Izard",
  "The Ideal Team Player: How to Recognize and Cultivate the Three Essential Virtues: A Leadership Fable": "Patrick M. Lencioni",
  "The Illusion of Money: Why Chasing Money Is Stopping You from Receiving It": "Kyle Cease",
  "The Immortal Life of Henrietta Lacks": "Rebecca Skloot",
  "The Immortal Mind: A Neurosurgeon's Case for the Existence of the Soul": "Michael Egnor, Denyse O'Leary",
  "The Inescapable Love of God: Second Edition": "Thomas Talbott",
  "The Infinite Game": "Simon Sinek",
  "The Innovators: How a Group of Hackers, Geniuses, and Geeks Created the Digital Revolution": "Walter Isaacson, Walter Isaacson - introduction",
  "The Instant AI Agency: How to Cash 6 & 7 Figure Checks in the New Digital Gold Rush Without Being a Tech Nerd": "Dan Wardrope",
  "The Intelligent Entrepreneur": "Bill Murphy Jr.",
  "The Jim Rohn Legacy Series: Timeless Wisdom on Success and Achievement": "Chris Widener",
  "The Joy Diet: 10 Daily Practices For a Happier Life": "Martha Beck",
  "The Knack: How Street-Smart Entrepreneurs Learn to Handle Whatever Comes Up": "Norm Brodsky, Bo Burlingham",
  "The Last Arrow: Save Nothing for the Next Life": "Erwin Raphael McManus",
  "The Law of Divine Compensation: On Work, Money, and Miracles": "Marianne Williamson",
  "The Law of Success: From the Master Mind to the Golden Rule (In Sixteen Lessons)": "Napoleon Hill",
  "The Laws of Human Nature": "Robert Greene",
  "The Laws of Lifetime Growth: Always Make Your Future Bigger than Your Past": "Dan Sullivan, Catherine Nomura",
  "The Laws of Manifestation: A Consciousness Classic": "David Spangler",
  "The Laws of Spirit: Teachings of the Mountain Sage (A Tale of Transformation)": "Dan Millman",
  "The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses": "Eric Ries",
  "The Light Beyond": "Raymond A. Moody MD PhD, Paul Perry",
  "The Listener's Bible: English Standard Version": "Fellowship for the Performing Arts",
  "The Little Things: Why You Really Should Sweat the Small Stuff": "Andy Andrews",
  "The Living Wisdom of Howard Thurman: A Visionary for Our Time": "Howard Thurman, Alice Walker - introduction, Michael Beckwith - introduction, Vincent Harding - introduction",
  "The Longevity Diet: Discover the New Science behind Stem Cell Activation and Regeneration to Slow Aging, Fight Disease, and Optimize Weight": "Valter Longo PhD",
  "The Lost Boy": "David Pelzer",
  "The Lost Choice: A Legend of Personal Discovery": "Andy Andrews",
  "The Lost Secret: Unlocking the Hidden Chapters of Napoleon Hill's Think and Grow Rich": "Monica Main, Jack Canfield - foreword",
  "The Lost World of Genesis One: Ancient Cosmology and the Origins Debate": "John H. Walton",
  "The Magic of Believing": "Claude M. Bristol",
  "The Magic of Thinking Big": "David Schwartz",
  "The Making of a Leader, Second Edition: Recognizing the Lessons and Stages of Leadership Development": "J. Robert Clinton",
  "The Man Who Would Be King and Other Stories": "Rudyard Kipling",
  "The Map of Heaven: How Science, Religion, and Ordinary People Are Proving the Afterlife": "Eben Alexander M.D. M.D.",
  "The Master Coach: Leading with Character, Building Connections, and Engaging in Extraordinary Conversations": "Gregg Thompson",
  "The Millionaire Booklet": "Grant Cardone",
  "The Millionaire Fastlane: Crack the Code to Wealth and Live Rich for a Lifetime": "MJ DeMarco",
  "The Millionaire Mind": "Thomas J. Stanley Ph.D., William D. Danko Ph.D.",
  "The Mind and the Brain: Neuroplasticity and the Power of Mental Force": "Jeffrey M. Schwartz, Sharon Begley",
  "The Miracle Equation: The Two Decisions That Move Your Biggest Goals from Possible, to Probable, to Inevitable": "Hal Elrod",
  "The Miracle Morning: The Not-So-Obvious Secret Guaranteed to Transform Your Life - Before 8AM": "Hal Elrod",
  "The Miracle of Mindfulness: An Introduction to the Practice of Meditation": "Thich Nhat Hanh",
  "The Miracle of Success": "Tom Hopkins",
  "The Money Code: Become a Millionaire with the Ancient Jewish Code": "H. W. Charles",
  "The Myths and the Magic of Real Estate Investing: A Selection from ABCs of Real Estate Investing": "Ken McElroy",
  "The New Codependency: Help and Guidance for Today's Generation": "Melody Beattie",
  "The New Testament for Everyone Audio Bible, Third Edition: A Fresh Translation": "N. T. Wright",
  "The New Testament in Its World: Audio Lectures, Part 1 of 2: An Introduction to the History, Literature, and Theology of the First Christians": "N. T. Wright, Michael F. Bird",
  "The New Testament in Its World: Audio Lectures, Part 2 of 2: An Introduction to the History, Literature, and Theology of the First Christians": "N. T. Wright, Michael F. Bird",
  "The Noticer Returns: Sometimes You Find Perspective, and Sometimes Perspective Finds You": "Andy Andrews",
  "The Noticer: Sometimes, All a Person Needs is a Little Perspective.": "Andy Andrews",
  "The Now Habit: A Strategic Program for Overcoming Procrastination and Enjoying Guilt-Free Play": "Neil Fiore",
  "The Nvidia Way: Jensen Huang and the Making of a Tech Giant": "Tae Kim",
  "The ONE Thing: The Surprisingly Simple Truth Behind Extraordinary Results": "Gary Keller, Jay Papasan",
  "The Obesity Code: Unlocking the Secrets of Weight Loss": "Dr. Jason Fung",
  "The Obstacle Is the Way: The Timeless Art of Turning Trials into Triumph": "Ryan Holiday",
  "The One Minute Millionaire: The Enlightened Way to Wealth": "Mark Victor Hansen, Robert G. Allen",
  "The Physics of God: Unifying Quantum Physics, Consciousness, M-Theory, Heaven, Neuroscience and Transcendence": "Amit Goswami, Joseph Selbie",
  "The Pocket Guide to High Ticket Selling: A 12-Phase Sales Script You Can Use to Sell Millions Over the Phone": "Dan Henry",
  "The Power of Ambition: Unleashing the Conquering Drive Within You!": "Jim Rohn",
  "The Power of Broke: How Empty Pockets, a Tight Budget, and a Hunger for Success Can Become Your Greatest Competitive Advantage": "Daymond John, Daniel Paisner",
  "The Power of Discipline: How to Use Self Control and Mental Toughness to Achieve Your Goals": "Daniel Walter",
  "The Power of Full Engagement: Managing Energy, Not Time, Is the Key to Performance and Personal Renewal": "Jim Loehr, Tony Schwartz",
  "The Power of Habit by Charles Duhigg - A 30-Minute Summary": "InstaRead Summary",
  "The Power of Habit: Why We Do What We Do in Life and Business": "Charles Duhigg",
  "The Power of I Am: Two Words That Will Change Your Life Today": "Joel Osteen",
  "The Power of Moments: Why Certain Experiences Have Extraordinary Impact": "Chip Heath, Dan Heath",
  "The Power of Neuroplasticity": "Shad Helmstetter PhD",
  "The Power of Now: A Guide to Spiritual Enlightenment": "Eckhart Tolle",
  "The Power of Positive Leadership: How and Why Positive Leaders Transform Teams and Organizations and Change the World": "Jon Gordon",
  "The Power of Positive Thinking: A Practical Guide to Mastering the Problems of Everyday Living": "Dr. Norman Vincent Peale",
  "The Power of Silence: Against the Dictatorship of Noise": "Robert Cardinal Sarah, Nicolas Diat, Michael J. Miller - translator",
  "The Power of Your Subconscious Mind: Updated": "Joseph Murphy",
  "The Power of Your Words": "E. W. Kenyon, Don Gossett",
  "The Power of a Positive Team: Proven Principles and Practices That Make Great Teams Great": "Jon Gordon",
  "The Power of a Whisper: Hearing God, Having the Guts to Respond": "Bill Hybels",
  "The Power of the Other: The startling effect other people have on you, from the boardroom to the bedroom and beyond-and what to do about it": "Henry Cloud",
  "The Power to Let Go and Live in the Now: Secrets of Being Unstoppable, Program 5": "Guy Finley",
  "The Practicing Mind: Developing Focus and Discipline in Your Life": "Thomas M. Sterner",
  "The Presentation Secrets of Steve Jobs: How to Be Insanely Great in Front of Any Audience": "Carmine Gallo",
  "The Principle of the Path: How To Get from Where You Are to Where You Want to Be": "Andy Stanley",
  "The Principles and Power of Vision: Keys to Achieving Personal and Corporate Destiny": "Dr. Myles Munroe",
  "The Problem of Pain": "C. S. Lewis",
  "The Problems of Work: Scientology Applied to the Workaday World": "L. Ron Hubbard",
  "The Prompt Recipe: A Practical Guide to Prompt Engineering and AI Interaction": "Alden Vale",
  "The Prophet": "Kahlil Gibran",
  "The Psychology of Money: Timeless Lessons on Wealth, Greed, and Happiness": "Morgan Housel",
  "The Quantum Story: A History in 40 Moments": "Jim Baggott",
  "The Return of the Prodigal Son: A Story of Homecoming": "Henri J. M. Nouwen",
  "The Richest Man in Babylon: The Success Secrets of the Ancients": "George S. Clason",
  "The Road Less Stupid": "Keith J. Cunningham",
  "The Road Less Traveled: A New Psychology of Love, Values, and Spiritual Growth, 25th Anniversary Edition": "M. Scott Peck",
  "The Robots Are Coming!: The Future of Jobs in the Age of Automation": "Andres Oppenheimer, Ezra E. Fitz - translator",
  "The Science of Getting Rich": "Wallace D. Wattles",
  "The Science of Personal Achievement: The 17 Universal Principles of Success": "Napoleon Hill",
  "The Science of Scaling: Grow Your Business Bigger and Faster Than You Think Possible": "Benjamin Hardy, Blake Erickson, Tony Robbins - introduction",
  "The Science of Storytelling": "Will Storr",
  "The Seat of the Soul: 25th Anniversary Edition": "Gary Zukav",
  "The Secret Code of Success: 7 Hidden Steps to More Wealth and Happiness": "Noah St. John",
  "The Secret Law of Attraction as Explained by Napoleon Hill": "Napoleon Hill",
  "The Secret of The Science of Getting Rich: Change Your Beliefs About Success and Money to Create the Life You Want": "Bob Proctor, Sandy Gallagher",
  "The Self-Talk Solution": "Shad Helmstetter",
  "The Shack": "Wm. Paul Young",
  "The Six Figure Second Income: How to Start and Grow a Successful Online Business Without Quitting Your Day Job": "Jonathan Rozek, David Lindahl",
  "The Small and the Mighty: Twelve Unsung Americans Who Changed the Course of History, from the Founding to the Civil Rights Movement": "Sharon McMahon",
  "The Snowball: Warren Buffett and the Business of Life": "Alice Schroeder",
  "The Southwest Airlines Way: Using the Power of Relationships to Achieve High Performance": "Jody Hoffer Gittell",
  "The Spirituality of Imperfection: Storytelling and the Search for Meaning": "Katherine Ketcham, Ernest Kurtz",
  "The Start-up of You: Adapt to the Future, Invest in Yourself, and Transform Your Career": "Reid Hoffman, Ben Casnocha",
  "The Steve Jobs Way: iLeadership for a New Generation": "Jay Elliot, William L. Simon",
  "The Story Selling Secret: A Simple, 5-Step Blueprint For Using Personal Stories To Create Emotional Connections, Make Yourself Unique, and Increase Sales": "Jim Edwards",
  "The Success Principles (Live)": "Jack Canfield",
  "The Success Principles: How to Get From Where You Are to Where You Want to Be": "Jack Canfield, Janet Switzer",
  "The Supernatural Power of a Transformed Mind, Expanded Edition: Access to a Life of Miracles": "Bill Johnson",
  "The Talent Code: Unlocking the Secret of Skill in Sports, Art, Music, Math, and Just About Anything": "Daniel Coyle",
  "The TenX Rule: The Only Difference Between Success and Failure": "Grant Cardone",
  "The Things They Carried": "Tim O'Brien",
  "The Things You Can See Only When You Slow Down: How to Be Calm and Mindful in a Fast-Paced World": "Haemin Sunim, Haemin Sunim - translation, Chi-Young Kim - translation",
  "The Three Pillars of Spiritual Power: Secrets of Being Unstoppable, Program 2": "Guy Finley",
  "The Traveler's Gift": "Andy Andrews",
  "The Ultimate Bob Proctor Library: The Legendary Personal Development Philosopher, Speaker, and Teacher": "Bob Proctor",
  "The Ultimate Jim Rohn Library": "Jim Rohn",
  "The Ultimate Sales Machine": "Chet Holmes",
  "The Uncontrolling Love of God: An Open and Relational Account of Providence": "Thomas Jay Oord",
  "The Universal Christ: How a Forgotten Reality Can Change Everything We See, Hope for, and Believe": "Richard Rohr",
  "The Untethered Soul: The Journey Beyond Yourself": "Michael A. Singer",
  "The Vision-Driven Leader: 10 Questions to Focus Your Efforts, Energize Your Team, and Scale Your Business": "Michael Hyatt",
  "The Voice of the Heart: A Call to Full Living": "Chip Dodd",
  "The Volunteer Revolution: Unleashing the Power of Everybody": "Bill Hybels",
  "The Wahls Protocol: How I Beat Progressive MS Using Paleo Principles and Functional Medicine": "Terry Wahls, Eve Adamson",
  "The Warren Buffett Portfolio: Mastering the Power of the Focus Investment Strategy": "Robert G. Hagstrom",
  "The Warren Buffett Way": "Robert Hagstrom",
  "The Warrior Poet Way: A Guide to Living Free and Dying Well": "John Lovell",
  "The Way of Peace": "James Allen",
  "The Way of the Warrior: An Ancient Path to Inner Peace": "Erwin Raphael McManus",
  "The Way of the Wolf: Straight Line Selling: Master the Art of Persuasion, Influence, and Success": "Jordan Belfort",
  "The Willpower Instinct: How Self-Control Works, Why It Matters, and What You Can Do to Get More of It": "Kelly McGonigal Ph.D.",
  "The Wisdom Jesus: Transforming Heart and Mind - A New Perspective on Christ and His Message": "Cynthia Bourgeault",
  "The Wisdom of Sundays: Life-Changing Insights from Super Soul Conversations": "Oprah Winfrey",
  "The Wright Brothers: a Biography": "Fred C. Kelly",
  "There's a Customer Born Every Minute: P.T. Barnum's Amazing 10 \"Rings of Power\" for Creating Fame, Fortune, and a Business Empire Today -- Guaranteed!": "Joe Vitale, Jeffrey Gitomer - Foreword",
  "They Walked with God: 40 Bible Characters Who Inspire Us": "Max Lucado",
  "Think Better, Live Better: A Victorious Life Begins in Your Mind": "Joel Osteen",
  "Think Like a Freak: The Authors of Freakonomics Offer to Retrain Your Brain": "Steven D. Levitt, Stephen J. Dubner",
  "Think and Grow Rich": "Napoleon Hill",
  "Think and Grow Rich: Instant Motivator": "Napoleon Hill",
  "Thinking Big: Achieving Greatness One Thought at a Time": "Zig Ziglar, Les Brown, Larry Iverson, Laura Stack, Bob Proctor, Marcia Wieder, Chris Widener, Sheila Murray Bethel, Mark Sanborn",
  "This Year I Will: How to Finally Change a Habit, Keep a Resolution, or Make a Dream Come True": "M. J. Ryan",
  "Thou Shall Prosper: Ten Commandments for Making Money": "Rabbi Daniel Lapin",
  "Thoughts Are Things: Turning Your Idea Into Realities, The Think and Grow Rich\u00ae series": "Bob Proctor, Greg S. Reid",
  "Time is a Tool: How to Scale Your Company 10x Faster": "Benjamin Hardy, Blake Erickson",
  "Timeless Wisdom with Dennis Prager": "Salem Podcast Network",
  "Too Busy Not to Pray: Slowing Down to Be With God": "Bill Hybels",
  "Tools of Titans: The Tactics, Routines, and Habits of Billionaires, Icons, and World-Class Performers": "Tim Ferriss",
  "Trading for a Living: Psychology, Trading Tactics, Money Management": "Alexander Elder",
  "Trailer": "Stephen Curry, Alex Vespestad, Stefan Marolachakis",
  "Train Your Mind to Be Successful: Attract and Get Anything You Want in Life": "Sayra S. Montes",
  "Tribes: We Need You to Lead Us": "Seth Godin",
  "Trump: The Art of the Deal": "Donald J. Trump, Tony Schwartz",
  "Undivided": "Neal Shusterman",
  "Unique: Telling Your Story in the Age of Brands and Social Media": "Phil Cooke",
  "Unleash the Power of Storytelling: Win Hearts, Change Minds, Get Results": "Rob Biesenbach",
  "Unlimited Power": "Tony Robbins",
  "Unoffendable: How Just One Change Can Make All of Life Better": "Brant Hansen",
  "Unscripted: Life, Liberty, and the Pursuit of Entrepreneurship": "MJ DeMarco",
  "Unshakeable: Your Financial Freedom Playbook": "Tony Robbins",
  "Unsouled": "Neal Shusterman",
  "Unwholly": "Neal Shusterman",
  "Up the Organization: How to Stop the Corporation from Stifling People and Strangling Profits, Commemorative Edition": "Robert C. Townsend, Warren Bennis",
  "Virtual Freedom: How to Work with Virtual Staff to Buy More Time, Become More Productive, and Build Your Dream Business": "Chris Ducker",
  "Waiting on God: Today's Best Teachers of the Bible, Volume 1": "Francis Chan, James MacDonald, John Ortberg, Bill Hybels",
  "Walking with God through Pain and Suffering": "Timothy Keller",
  "We Who Wrestle with God: Perceptions of the Divine": "Jordan B. Peterson",
  "Wealth Can't Wait: Avoid the 7 Wealth Traps, Implement the 7 Business Pillars, and Complete a Life Audit Today!": "David Osborn, Paul Morris",
  "Weight Loss Motivation": "Benjamin Bonetti",
  "Welcome to Your Teenager's Brain": "Abigail Baird, The Great Courses",
  "What Got You Here Won't Get You There: How Successful People Become Even More Successful": "Marshall Goldsmith, Mark Reiter",
  "What Happy People Know: Learn All About True Happiness and an Empowered Mindset": "Kendra Winston",
  "What I Know For Sure": "Oprah Winfrey",
  "What Is Leadership?: Defining Leadership for Personal Success": "John C. Maxwell, Les Brown, Sheila Bethel",
  "What to Say When You Talk to Your Self": "Shad Helmstetter PhD",
  "When Helping Hurts: How to Alleviate Poverty Without Hurting the Poor...and Yourself": "Steve Corbett, Brian Fikkert",
  "When: The Scientific Secrets of Perfect Timing": "Daniel H. Pink",
  "Where Children Run": "Karen Emilson",
  "Where the Crawdads Sing: Reese's Book Club": "Delia Owens",
  "Who Do You Want to Be a Hero To?: Answer Just One Question and Clarify Who You Can Always Be": "Dan Sullivan",
  "Who Not How: The Formula to Achieve Bigger Goals Through Accelerating Teamwork": "Dan Sullivan, Benjamin Hardy",
  "Who Was Albert Einstein?": "Jess Brallier",
  "Who You Are When No One's Looking: Choosing Consistency, Resisting Compromise": "Bill Hybels",
  "Why We Get Sick: The Hidden Epidemic at the Root of Most Chronic Disease - and How to Fight It": "Benjamin Bikman PhD",
  "Why We Sleep: Unlocking the Power of Sleep and Dreams": "Matthew Walker PhD",
  "Why We Want You to Be Rich: Two Men, One Message": "Donald J. Trump, Robert T. Kiyosaki",
  "Why the Rich Are Getting Richer": "Tom Wheelwright, Robert T. Kiyosaki",
  "Willpower Doesn't Work: Discover the Hidden Keys to Success": "Benjamin Hardy",
  "Winners Dream: A Journey from Corner Store to Corner Office": "Bill McDermott, Joanne Gordon",
  "Winning the War in Your Mind: Change Your Thinking, Change Your Life": "Craig Groeschel",
  "Write With AI: Guide for Fiction and Nonfiction Authors: Using Artificial Intelligence like ChatGPT to Generate Ideas, Produce Content, and Future-Proof Your Writing Career": "Rachelle Ayala",
  "You Are Not Your Own: Belonging to God in an Inhuman World": "Alan Noble",
  "You Are a Writer (So Start Acting Like One)": "Jeff Goins",
  "You Become What You Think About: How Your Mind Creates the World You Live in": "Vic Johnson",
  "You Can Work Your Own Miracles": "Napoleon Hill",
  "You Have a Book In You: Make Money with YOUR Story": "Mark Victor Hansen",
  "You Owe You: Ignite Your Power, Your Purpose, and Your Why": "Eric Thomas PhD, Chris Paul - introduction",
  "You Were Born Rich": "Bob Proctor",
  "Your Brain Is Always Listening: Tame the Hidden Dragons That Control Your Happiness, Habits, and Hang-Ups": "Daniel G. Amen",
  "Your Brain at Work: Strategies for Overcoming Distraction, Regaining Focus, and Working Smarter All Day Long": "David Rock",
  "Your Brain on Love: The Neurobiology of Healthy Relationships": "PsyD MFT Stan Tatkin",
  "Your First Listen": "test",
  "Your Right to Be Rich": "Napoleon Hill",
  "Your Word Is Your Wand": "Florence Scovel Shinn",
  "Zen Golf: Mastering the Mental Game": "Dr. Joseph Parent",
  "Zen Habits: Handbook for Life": "Leo Babauta",
  "Zorba the Greek": "Nikos Kazantzakis",
};
